# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\usuyus22\Desktop/auth\__main__.py/../design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(421, 285)
        font = QtGui.QFont()
        font.setFamily("Arial")
        LoginWindow.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(LoginWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 361, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.userLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.userLabel.setObjectName("userLabel")
        self.horizontalLayout.addWidget(self.userLabel)
        self.userEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.userEdit.setObjectName("userEdit")
        self.horizontalLayout.addWidget(self.userEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pwLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pwLabel.setObjectName("pwLabel")
        self.horizontalLayout_2.addWidget(self.pwLabel)
        self.pwEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.pwEdit.setInputMask("")
        self.pwEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwEdit.setObjectName("pwEdit")
        self.horizontalLayout_2.addWidget(self.pwEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.authUserButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.authUserButton.setObjectName("authUserButton")
        self.horizontalLayout_3.addWidget(self.authUserButton)
        self.newUserButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.newUserButton.setObjectName("newUserButton")
        self.horizontalLayout_3.addWidget(self.newUserButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.statusLabel = QtWidgets.QLabel(LoginWindow)
        self.statusLabel.setGeometry(QtCore.QRect(30, 210, 361, 48))
        self.statusLabel.setStyleSheet("font-size: 14pt;\n"
"color: #222288;\n"
"border: 1px solid black\n"
"")
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")

        self.retranslateUi(LoginWindow)
        self.authUserButton.clicked.connect(LoginWindow.login)
        self.newUserButton.clicked.connect(LoginWindow.signup)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Extremely Unsafe Authentication System"))
        self.userLabel.setText(_translate("LoginWindow", "Username"))
        self.pwLabel.setText(_translate("LoginWindow", "Password"))
        self.authUserButton.setText(_translate("LoginWindow", "Login"))
        self.newUserButton.setText(_translate("LoginWindow", "New User"))
